version: '3.9'

volumes:
  postgres-data:
  static-data:

services:
  server:
    build: 
      context: ./server
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:14.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  proxy:
    build: 
      context: ./proxy
    restart: always
    depends_on: 
      - server
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static