version: "3.9"
   
services:
  db:
    image: postgres:14.4
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  server:
    build:
      context: ./server
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/server
      - ./data/web:/vol/web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=LASDM22l!
      - DEBUG=1
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  client:
    build: ./client
    volumes: 
      - "./client:/app"
    depends_on:
      - server
    ports:
      - 80:80