# Generated by Django 4.0.6 on 2022-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_address',
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=35932182213, max_length=50),
            preserve_default=False,
        ),
    ]
